### ISSUE TITLE
Missing Password Policy authenticator connector

### ISSUE THREAD

**Issue by jonathanchris** [wso2-attic/is-connectors#67]
Hi I'm new to WSO2-IS and I'm having trouble finding the source for the Password Policy authenticator connector. I noticed that there are a few of the connectors from the IS store that aren't shown here. Or am I just looking in the wrong place?

**Comment by jonathanchris** [comment]
I found what I was looking for [here](https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy)
Sorry for the pre-emptive issue creation, Thanks!

**Comment by RKathees** [comment]
We restructured the connectors git repository with the following standard. Identity Server (IS) and Enterprise Service Bus(ESB) extensions source code are in wso2-extensions [1].
<product>-<position>-<type>-<domian>
eg:-
is-inbound-auth-passwordPolicy
is-outbound-provisioning-inwebo
esb-connector-twitter
esb-inbound-twitter

If you need to get the released connectors please refer the "tag" version e.g [2], the development will be done at master [3], and "wso2/esb-connectors" moved to 'attic' i.e https://github.com/wso2-attic/esb-connectors, and will depreciate​ soon.

[1] - https://github.com/wso2-extensions
[2] - https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy/tree/org.wso2.carbon.extension.identity.authenticator.passwordpolicy-1.0.1
[3] - https://github.com/wso2-extensions/identity-outbound-auth-passwordPolicy
